FROM --platform=linux/amd64 openjdk:18-jdk-slim

WORKDIR /usr/src/app

COPY target/ckn-stream-processors-0.1-SNAPSHOT.jar .

EXPOSE 9092

# Setting env variables, move this to docker-compose if required
ENV CKN_BROKERS=localhost:9092
ENV ORACLE_ACC_CRITICAL_THRESHOLD=0.5
ENV ORACLE_INPUT_TOPIC=oracle-events
ENV ORACLE_ACC_ALERT_TOPIC=oracle-alerts
ENV APP_ID=ckn-camera-traps-oracle-processor

CMD ["java", "-cp", "ckn-stream-processors-0.1-SNAPSHOT.jar", "edu.d2i.ckn.OracleAccAlertProcessor"]
